using System;
using System.Text.Json.Serialization;

namespace Redis.OM.Modeling
{
    /// <summary>
    /// Method for converting a field into a vector.
    /// </summary>
    public abstract class VectorizerAttribute : JsonConverterAttribute
    {
        /// <summary>
        /// Gets the vector Type generated by the vectorizer.
        /// </summary>
        public abstract VectorType VectorType { get; }

        /// <summary>
        /// Gets the vector dimension of the vectors generated by the vectorizer.
        /// </summary>
        public abstract int Dim { get; }

        /// <summary>
        /// Converts the provided object to a vector.
        /// </summary>
        /// <param name="obj">the object to convert.</param>
        /// <returns>A byte array containing the vectorized data.</returns>
        public abstract byte[] Vectorize(object obj);

        /// <summary>
        /// Creates the json converter fulfilled by this attribute.
        /// </summary>
        /// <param name="typeToConvert">The type to convert.</param>
        /// <returns>The Json Converter.</returns>
        public override JsonConverter? CreateConverter(Type typeToConvert)
        {
            return new VectorJsonConverter(this);
        }
    }
}