FROM redis/redis-stack-server

ENV SENTINEL_QUORUM 2
ENV SENTINEL_DOWN_AFTER 1000
ENV SENTINEL_FAILOVER 1000

RUN mkdir -p /redis

WORKDIR /redis

COPY sentinel.conf .
COPY startup.sh /usr/local/bin/

RUN chown redis:redis /redis/* 
RUN chmod +x /usr/local/bin/startup.sh

EXPOSE 26379

ENTRYPOINT [ "startup.sh" ]